import { IMovie } from "../models/movie.model";

export const moviesMock: IMovie[]=[
  {id: 1, title: "Harry Potter and the sorcerer's stone", premiere: 2001, image: '../../assets/HarryPotter1.jpg', qualification: 5, description: "The Chamber of Secrets was home to an ancient Basilisk, which, according to legend, was intended to be used to purge the area of Muggle-born students.", type: "Fiction"},
  {id: 2,title: "Harry Potter and the chamber of secret", premiere: 2002, image: '../../assets/harryPotter2.jpg', qualification: 5, description: "The Chamber of Secrets was home to an ancient Basilisk, which, according to legend, was intended to be used to purge the area of Muggle-born students.", type: "Fiction"},
  {id: 3, title: "Harry Potter and the prisioners of Azkaban", premiere: 2004, image: '../../assets/HarryPotter3.jpg', qualification: 5, description: "Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.", type: "Fiction"},
  {id: 4, title: "Harry Potter and the goblet of fire", premiere: 2001, image: '../../assets/HarryPotter4.jpg', qualification: 5, description: "The Chamber of Secrets was home to an ancient Basilisk, which, according to legend, was intended to be used to purge the area of Muggle-born students.", type: "Fiction"},
  {id: 5, title: "Harry Potter and the order of pheonix", premiere: 2002, image: '../../assets/HarryPotter5.jpg', qualification: 5, description: "The Chamber of Secrets was home to an ancient Basilisk, which, according to legend, was intended to be used to purge the area of Muggle-born students.", type: "Fiction"},
  {id: 6, title: "Harry Potter and the half blood prince", premiere: 2004, image: '../../assets/HarryPotter6.jpg', qualification: 5, description: "Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.", type: "Fiction"},
  {id: 7, title: "Harry Potter and deadly oh hallow", premiere: 2001, image: '../../assets/HarryPotter7.jpg', qualification: 5, description: "The Chamber of Secrets was home to an ancient Basilisk, which, according to legend, was intended to be used to purge the area of Muggle-born students.", type: "Fiction"},
  {id: 8, title: "Harry Potter and the chamber of secret", premiere: 2002, image: '../../assets/harryPotter2.jpg', qualification: 5, description: "The Chamber of Secrets was home to an ancient Basilisk, which, according to legend, was intended to be used to purge the area of Muggle-born students.", type: "Fiction"},
  {id: 9, title: "Harry Potter and the prisioners of Azkaban", premiere: 2004, image: '../../assets/HarryPotter3.jpg', qualification: 5, description: "Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.", type: "Fiction"},
];
